# Generated by Django 5.0.3 on 2024-03-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mess',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
    ]
